build:
  before_script:
    - /bin/true
  stage: build
  script:
    - npm i
  artifacts:
    expire_in: 1 day
    paths:
      - node_modules/
test:
  script:
    - make tests
  dependencies:
    - build
