language: node_js
node_js:
  - "6.1"
  - "6.0"
  - "5.11"
  - "5.10"
  - "5.9"
  - "5.8"
  - "5.7"
  - "5.6"
  - "5.5"
  - "5.4"
  - "5.3"
  - "5.2"
  - "5.1"
  - "5.0"
  - "4.4"
  - "4.3"
  - "4.2"
  - "4.1"
  - "4.0"
before_script:
  - npm install -g mocha
  - make tests
script: mocha
env:
  - VER=13.6 TEST=ALL
  - VER=13.5 TEST=ALL
  - VER=13.4 TEST=ALL
  - VER=13.3 TEST=ALL
  - VER=13.2 TEST=ALL
  - VER=13.1 TEST=ALL
  - VER=12.4 TEST=ALL
  - VER=12.3 TEST=ALL
  - VER=12.2 TEST=ALL
  - VER=12.1 TEST=ALL
  - VER=12.0 TEST=ALL
